import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from './app-routing.module.tns';
import { AppComponent } from './app.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { CreateComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-udara/create/create.component';
import { SuCreateComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-udara/su-create/su-create.component';
import { SuReadComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-udara/su-read/su-read.component';
import { SuUpdateComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-udara/su-update/su-update.component';
import { SuDeleteComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-udara/su-delete/su-delete.component';
import { SdCreateComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-darat/sd-create/sd-create.component';
import { SdReadComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-darat/sd-read/sd-read.component';
import { SdUpdateComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-darat/sd-update/sd-update.component';
import { SdDeleteComponent } from './master-data/master-data-peralatan/kategori-peralatan/sisi-darat/sd-delete/sd-delete.component';
import { YandarCreateComponent } from './master-data/master-data-peralatan/kategori-peralatan/yandar/yandar-create/yandar-create.component';
import { YandarReadComponent } from './master-data/master-data-peralatan/kategori-peralatan/yandar/yandar-read/yandar-read.component';
import { YandarUpdateComponent } from './master-data/master-data-peralatan/kategori-peralatan/yandar/yandar-update/yandar-update.component';
import { YandarDeleteComponent } from './master-data/master-data-peralatan/kategori-peralatan/yandar/yandar-delete/yandar-delete.component';


// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    CreateComponent,
    SuCreateComponent,
    SuReadComponent,
    SuUpdateComponent,
    SuDeleteComponent,
    SdCreateComponent,
    SdReadComponent,
    SdUpdateComponent,
    SdDeleteComponent,
    YandarCreateComponent,
    YandarReadComponent,
    YandarUpdateComponent,
    YandarDeleteComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
